"""Layer 5a — build the HTML daily digest.

Two sections (International first — it's the priority pipeline, then India),
each split into Strong (60+) and Worth Reviewing (40-59), sorted by score.
Returns ``(subject, html)`` for the sender.
"""

from __future__ import annotations

from datetime import date
from html import escape

from processing.models import Pipeline, ScoredJob, VisaStatus

STRONG = 60


def _tech_summary(sj: ScoredJob, limit: int = 4) -> str:
    from common import config
    text = f"{sj.title} {sj.raw.description}".lower()
    hits = [k for k in config.scoring()["tech_stack_keywords"] if k in text]
    pretty = []
    for h in hits:
        pretty.append({"llm": "LLMs", "rag": "RAG", "nlp": "NLP",
                       "mlops": "MLOps"}.get(h, h.title()))
        if len(pretty) >= limit:
            break
    return ", ".join(dict.fromkeys(pretty)) or "—"


def _card(rank: int, sj: ScoredJob) -> str:
    color = "#16a34a" if sj.composite_score >= STRONG else "#ca8a04"
    visa = ""
    if sj.pipeline == Pipeline.INTERNATIONAL:
        vcolor = {"YES": "#16a34a", "UNKNOWN": "#6b7280",
                  "NO": "#dc2626"}.get(sj.visa_status.value, "#6b7280")
        visa = (f'<span style="color:{vcolor};font-weight:600">'
                f'Visa: {escape(sj.visa_status.value)}</span> &nbsp;|&nbsp; ')
    salary = ""
    if sj.salary_estimate:
        salary = f' &nbsp;|&nbsp; ~{escape(sj.salary_estimate)}'
    loc = escape(sj.location or "—")
    company = escape(sj.company or "Unknown")
    title = escape(sj.title)
    url = escape(sj.url or "#")
    flags = (f'<div style="color:#b45309;font-size:12px;margin-top:2px">'
             f'⚠ {escape(sj.red_flags)}</div>' if sj.red_flags else "")
    return f"""
    <tr><td style="padding:10px 0;border-bottom:1px solid #eee">
      <span style="display:inline-block;min-width:42px;font-weight:700;
        color:{color}">[{sj.composite_score}]</span>
      <strong>{rank}. {title}</strong> — {company}, {loc}
      <div style="color:#555;font-size:13px;margin-top:2px">
        {visa}Stack: {_tech_summary(sj)}{salary}
      </div>
      <div style="margin-top:2px"><a href="{url}" style="color:#2563eb;
        font-size:13px">→ Apply / view listing</a></div>
      {flags}
    </td></tr>"""


def _section(name: str, jobs: list[ScoredJob], top_n: int = 10) -> str:
    strong = [j for j in jobs if j.composite_score >= STRONG][:top_n]
    review = [j for j in jobs if j.composite_score < STRONG][:top_n]
    if not strong and not review:
        body = ('<tr><td style="color:#888;padding:10px 0">'
                'No matches today.</td></tr>')
    else:
        body = ""
        if strong:
            body += ('<tr><td style="padding-top:8px;font-weight:700">'
                     '🟢 STRONG MATCHES (60+)</td></tr>')
            body += "".join(_card(i, j) for i, j in enumerate(strong, 1))
        if review:
            body += ('<tr><td style="padding-top:14px;font-weight:700">'
                     '🟡 WORTH REVIEWING (40-59)</td></tr>')
            body += "".join(_card(i, j)
                            for i, j in enumerate(review, len(strong) + 1))
    return f"""
    <h2 style="font-size:18px;margin:24px 0 4px">{escape(name)}
      <span style="color:#888;font-weight:400;font-size:14px">
      ({len(jobs)} jobs)</span></h2>
    <table width="100%" cellpadding="0" cellspacing="0"
      style="border-collapse:collapse">{body}</table>"""


def build_html(scored: list[ScoredJob], sheet_url: str = "") -> tuple[str, str]:
    today = date.today().isoformat()
    intl = [j for j in scored if j.pipeline == Pipeline.INTERNATIONAL]
    india = [j for j in scored if j.pipeline == Pipeline.INDIA]
    intl.sort(key=lambda j: j.composite_score, reverse=True)
    india.sort(key=lambda j: j.composite_score, reverse=True)

    # ASCII-only subject: non-ASCII in an unencoded Subject header mojibakes in
    # some mail clients. The HTML body (utf-8) keeps its emoji/em-dashes.
    subject = f"JobRadar Daily Digest - {today} - {len(scored)} jobs found"
    footer = ""
    if sheet_url:
        footer = (f'<p style="margin-top:24px"><a href="{escape(sheet_url)}" '
                  f'style="color:#2563eb">Open full tracker in Google Sheets →'
                  f'</a></p>')

    html = f"""<!doctype html><html><body style="font-family:-apple-system,
      Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#111;max-width:680px;
      margin:0 auto;padding:16px">
      <h1 style="font-size:22px;margin:0 0 2px">JobRadar Daily Digest</h1>
      <div style="color:#888">{today} · {len(scored)} scored jobs
        ({len(intl)} international, {len(india)} India)</div>
      {_section("🌍 International Pipeline", intl)}
      {_section("🇮🇳 India Pipeline", india)}
      {footer}
      <p style="color:#aaa;font-size:12px;margin-top:24px">
        Generated by JobRadar. Pick your top 5-8 and let Claude handle the
        application materials.</p>
    </body></html>"""
    return subject, html
